name: docker_steps
description: "Pushes built artifacts to Docker"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  docker_context:
    description: "Password for image registry"
    required: true

runs:
  using: "composite"
  steps:
      - uses: docker/setup-buildx-action@v1
      - name: login to GHCR
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}
      - name: build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{inputs.docker_context}}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.fld_schedule }}:latest
